version: "1.0"
info:
  model: int-scaffold
packages:
- name: MCSPPPGitKusiProject
  gitServerName: RajniVCAccount
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMSTest
  gitServerName: RajniVCAccount
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMS2waySSL
  gitServerName: RajniVCAccount
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  gitServerName: RajniVCAccount
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: DADA_GlobalVariable1
  gitServerName: MJANGIT
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: gv25var
- name: SIQACloudStreamsTests
  gitServerName: MJANGIT
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
